import json

from pathlib import Path
 
 
def _write_modality_json_and_config(
    self,
    modality_path,
    config_path,
    embodiment_name,       # e.g. "ur5" -> produces `rendered_ur5_config` + EmbodimentTag lookup
    joints,
    n_pinch,
    video_key,
    joint_key_name="target_pose",   # must match your ModalityConfig.modality_keys usage
    gripper_key_name="gripper",
    action_horizon=16,
    joint_action_rep="ABSOLUTE",     # ActionRepresentation.<value>
    joint_action_type="NON_EEF",     # ActionType.<value> — NON_EEF for joint-space, EEF for end-effector
    gripper_action_rep="ABSOLUTE",
    gripper_action_type="NON_EEF",
    embodiment_tag="NEW_EMBODIMENT", # EmbodimentTag.<value>
):
    """
    State/action layout built above:
        [joint_0/rot_0 .. joint_0/rot_k, joint_1/rot_0 .. , ..., pinch_0 .. pinch_{n_pinch-1}]
    i.e. rotation fields per joint in canonical order, then pinch dims.
    Assumes your action-building code produces the SAME layout — verify that
    separately, this doesn't check it.
 
    joint_key_name / gripper_key_name control BOTH the modality.json field
    names and the ModalityConfig.modality_keys strings in the generated
    config, so the two files are guaranteed to agree.
    """
    n_rotation_dims = len(joints) - 1
 
    # ---- 1. modality.json --------------------------------------------------
    modality = {
        "state": {
            joint_key_name: {"start": 0, "end": n_rotation_dims},
            gripper_key_name: {"start": n_rotation_dims, "end": n_rotation_dims + n_pinch},
        },
        "action": {
            joint_key_name: {"start": 0, "end": n_rotation_dims},
            gripper_key_name: {"start": n_rotation_dims, "end": n_rotation_dims + n_pinch},
        },
        "video": {
            video_key: {"original_key": f"observation.images.{video_key}"}
        },
        "annotation": {
            "human.action.task_description": {}
        },
    }
 
    modality_path = Path(modality_path)
    modality_path.parent.mkdir(parents=True, exist_ok=True)
    with open(modality_path, "w") as f:
        json.dump(modality, f, indent=2)
 
    print(
        f"wrote {modality_path} | joints={joints} | "
        f"rot_dims={n_rotation_dims} | pinch_dims={n_pinch}"
    )
 
    # ---- 2. rendered_<embodiment_name>_config.py ---------------------------
    var_name = f"rendered_{embodiment_name}_config"
 
    config_src = f'''# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Auto-generated by write_modality_config.py — do not hand-edit field names
# without re-running the generator, or this will drift from modality.json.
 
from gr00t.configs.data.embodiment_configs import register_modality_config
from gr00t.data.embodiment_tags import EmbodimentTag
from gr00t.data.types import (
    ActionConfig,
    ActionFormat,
    ActionRepresentation,
    ActionType,
    ModalityConfig,
)
 
 
{var_name} = {{
    # Video: current frame only; keys must match "video" entries in meta/modality.json
    "video": ModalityConfig(
        delta_indices=[0],
        modality_keys=["{video_key}"],
    ),
    # State: current proprioceptive reading; keys must match "state" entries in meta/modality.json
    "state": ModalityConfig(
        delta_indices=[0],
        modality_keys=[
            "{joint_key_name}",
            "{gripper_key_name}",
        ],
    ),
    # Action: {action_horizon}-step prediction horizon; one ActionConfig per modality key
    "action": ModalityConfig(
        delta_indices=list(range(0, {action_horizon})),
        modality_keys=[
            "{joint_key_name}",
            "{gripper_key_name}",
        ],
        action_configs=[
            ActionConfig(
                rep=ActionRepresentation.{joint_action_rep},
                type=ActionType.{joint_action_type},
                format=ActionFormat.DEFAULT,
            ),
            ActionConfig(
                rep=ActionRepresentation.{gripper_action_rep},
                type=ActionType.{gripper_action_type},
                format=ActionFormat.DEFAULT,
            ),
        ],
    ),
    # Language: task instruction from annotation field in the dataset
    "language": ModalityConfig(
        delta_indices=[0],
        modality_keys=["annotation.human.task_description"],
    ),
}}
 
register_modality_config({var_name}, embodiment_tag=EmbodimentTag.{embodiment_tag})
'''
 
    config_path = Path(config_path)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        f.write(config_src)
 
    print(f"wrote {config_path} | var={var_name} | embodiment_tag={embodiment_tag}")
 


def write_modality_json(self, modality_path, joints, n_pinch, video_key, task):
        """
        State/action layout built above:
            [joint_0/rot_0 .. joint_0/rot_k, joint_1/rot_0 .. , ..., pinch_0 .. pinch_{n_pinch-1}]
        i.e. rotation fields per joint in canonical order, then pinch dims.
        Assumes your action-building code produces the SAME layout — verify that
        separately, this doesn't check it.
        """
        n_rotation_dims = (len(joints) - 1)

        modality = {
            "state": {
                "joint_rotation": {"start": 0, "end": n_rotation_dims},
                "gripper": {"start": n_rotation_dims, "end": n_rotation_dims + n_pinch},
            },
            "action": {
                "joint_rotation": {"start": 0, "end": n_rotation_dims},
                "gripper": {"start": n_rotation_dims, "end": n_rotation_dims + n_pinch},
            },
            "video": {
                video_key: {"original_key": f"observation.images.{video_key}"}
            },
            "annotation": {
                "human.action.task_description": {}
            },
        }
        modality_path.parent.mkdir(parents=True, exist_ok=True)
        with open(modality_path, "w") as f:
            json.dump(modality, f, indent=2)

        print(f"wrote {modality_path} | joints={joints} | rot_dims={n_rotation_dims} | pinch_dims={n_pinch}")